# Generated by Django 6.0 on 2025-12-09 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryattribute',
            old_name='is_filterble',
            new_name='is_filterable',
        ),
        migrations.CreateModel(
            name='CategoryAttributeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='catalog.categoryattribute')),
            ],
            options={
                'verbose_name': 'Вариант атрибута',
                'verbose_name_plural': 'Варианты атрибута',
                'unique_together': {('attribute', 'value')},
            },
        ),
    ]
